SELECT
    OI.ITEMID                  AS ITEMID,
    I.ITEMNAME                 AS ITEMNAME,
    I.IMAGEFILE                AS ITEMIMAGE,
    SUM(OI.ORDERQTY)           AS TOTALQUANTITY,
    SUM(OI.ORDERQTY * I.PRICE) AS TOTALSALESAMOUNT
FROM
    ORDERSITEM OI
    JOIN ITEM I
    ON OI.ITEMID = I.ITEMID
WHERE
    I.SUPPLIERID = ?
GROUP BY
    OI.ITEMID, I.ITEMNAME, I.IMAGEFILE